[package]
name = "marketplace"
version = "0.1.0"
description = "Marketplace — list/buy NFT items, burn NFT, mint MagicToken to seller"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "marketplace"

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
no-entrypoint = []
no-idl = []
no-log-panics = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
mpl-token-metadata = { workspace = true }
item_nft = { path = "../item_nft", features = ["cpi"] }
magic_token = { path = "../magic_token", features = ["cpi"] }
