[package]
name = "item_nft"
version = "0.1.0"
description = "Bootstrap scaffold for the item_nft program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "item_nft"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "resource_manager/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
mpl-token-metadata = "5.1.1"
resource_manager = { path = "../resource_manager", features = ["cpi"] }
shared = { path = "../../shared" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
