use anchor_lang::prelude::*;
use mpl_token_metadata;
use anchor_spl::{
    associated_token::AssociatedToken,
    token::Token,
    token_2022::Token2022,
    token_interface::Mint,
};
use resource_manager::{cpi::accounts::BurnResource, state::GameConfig};
use item_nft::cpi::accounts::MintNft;
use crate::{constants::RECIPES, errors::CraftingError};

#[derive(Accounts)]
#[instruction(item_type: u8)]
pub struct CraftItem<'info> {
    /// The player wallet — must sign to authorize resource burns.
    #[account(mut)]
    pub player_wallet: Signer<'info>,

    /// New NFT mint keypair, generated by client. Initialized by item_nft::mint_nft CPI.
    #[account(mut)]
    pub nft_mint: Signer<'info>,

    /// GameConfig from resource_manager — provides mint address validation.
    #[account(seeds = [b"game_config"], bump = game_config.bump, seeds::program = resource_manager::ID)]
    pub game_config: Box<Account<'info, GameConfig>>,

    /// CHECK: This program's cpi_auth PDA — passed to resource_manager and item_nft as caller identity.
    #[account(seeds = [b"cpi_auth"], bump)]
    pub cpi_auth: AccountInfo<'info>,

    /// CHECK: resource_mint_auth PDA from resource_manager — holds mint authority.
    #[account(mut, seeds = [b"resource_mint_auth"], bump, seeds::program = resource_manager::ID)]
    pub resource_mint_auth: AccountInfo<'info>,

    // ── 6 resource mints (Token-2022) ──────────────────────────────────────────
    #[account(mut, constraint = mint0.key() == game_config.resource_mints[0])]
    pub mint0: Box<InterfaceAccount<'info, Mint>>,
    #[account(mut, constraint = mint1.key() == game_config.resource_mints[1])]
    pub mint1: Box<InterfaceAccount<'info, Mint>>,
    #[account(mut, constraint = mint2.key() == game_config.resource_mints[2])]
    pub mint2: Box<InterfaceAccount<'info, Mint>>,
    #[account(mut, constraint = mint3.key() == game_config.resource_mints[3])]
    pub mint3: Box<InterfaceAccount<'info, Mint>>,
    #[account(mut, constraint = mint4.key() == game_config.resource_mints[4])]
    pub mint4: Box<InterfaceAccount<'info, Mint>>,
    #[account(mut, constraint = mint5.key() == game_config.resource_mints[5])]
    pub mint5: Box<InterfaceAccount<'info, Mint>>,

    /// CHECK: 6 player resource ATAs (Token-2022). Each one is validated by the
    /// burn_resource CPI via its associated_token constraints.
    #[account(mut)]
    pub ata0: UncheckedAccount<'info>,
    #[account(mut)]
    pub ata1: UncheckedAccount<'info>,
    #[account(mut)]
    pub ata2: UncheckedAccount<'info>,
    #[account(mut)]
    pub ata3: UncheckedAccount<'info>,
    #[account(mut)]
    pub ata4: UncheckedAccount<'info>,
    #[account(mut)]
    pub ata5: UncheckedAccount<'info>,

    // ── item_nft CPI accounts ─────────────────────────────────────────────────
    /// CHECK: nft_authority PDA from item_nft — holds mint/freeze authority over NFTs.
    #[account(seeds = [b"nft_authority"], bump, seeds::program = item_nft::ID)]
    pub nft_authority: AccountInfo<'info>,

    /// CHECK: Metaplex metadata account for the new NFT mint. Derived client-side.
    #[account(mut)]
    pub metadata: AccountInfo<'info>,

    /// CHECK: Metaplex master edition account for the new NFT mint. Derived client-side.
    #[account(mut)]
    pub master_edition: AccountInfo<'info>,

    /// CHECK: ItemMetadata PDA created by item_nft::mint_nft. Derived from nft_mint.
    #[account(
        mut,
        seeds = [b"item_metadata", nft_mint.key().as_ref()],
        bump,
        seeds::program = item_nft::ID,
    )]
    pub item_metadata: AccountInfo<'info>,

    /// Recipient's ATA for the NFT (classic SPL Token). Must be created by client before calling.
    /// CHECK: Validated by item_nft::mint_nft CPI (associated_token constraints there).
    #[account(mut)]
    pub recipient_nft_ata: AccountInfo<'info>,

    /// CHECK: resource_manager program.
    #[account(address = resource_manager::ID)]
    pub resource_manager_program: AccountInfo<'info>,

    /// CHECK: item_nft program.
    #[account(address = item_nft::ID)]
    pub item_nft_program: AccountInfo<'info>,

    /// CHECK: Metaplex Token Metadata program — required for item_nft CPI.
    #[account(address = mpl_token_metadata::ID)]
    pub token_metadata_program: AccountInfo<'info>,

    pub associated_token_program: Program<'info, AssociatedToken>,
    pub token_2022_program: Program<'info, Token2022>,
    pub token_program: Program<'info, Token>,
    pub system_program: Program<'info, System>,
}

/// Craft an NFT item. Burns resources per recipe, then mints the NFT via item_nft CPI.
pub fn handler(ctx: Context<CraftItem>, item_type: u8) -> Result<()> {
    require!(item_type < 4, CraftingError::InvalidItemType);

    let recipe = RECIPES[item_type as usize];

    let cpi_bump = ctx.bumps.cpi_auth;
    let signer_seeds: &[&[&[u8]]] = &[&[b"cpi_auth", &[cpi_bump]]];

    let mints = [
        ctx.accounts.mint0.to_account_info(),
        ctx.accounts.mint1.to_account_info(),
        ctx.accounts.mint2.to_account_info(),
        ctx.accounts.mint3.to_account_info(),
        ctx.accounts.mint4.to_account_info(),
        ctx.accounts.mint5.to_account_info(),
    ];

    let atas = [
        ctx.accounts.ata0.to_account_info(),
        ctx.accounts.ata1.to_account_info(),
        ctx.accounts.ata2.to_account_info(),
        ctx.accounts.ata3.to_account_info(),
        ctx.accounts.ata4.to_account_info(),
        ctx.accounts.ata5.to_account_info(),
    ];

    // Burn each resource in the recipe.
    for (resource_id, &amount) in recipe.iter().enumerate() {
        if amount == 0 {
            continue;
        }

        let burn_accounts = BurnResource {
            cpi_auth: ctx.accounts.cpi_auth.to_account_info(),
            game_config: ctx.accounts.game_config.to_account_info(),
            mint: mints[resource_id].clone(),
            source_ata: atas[resource_id].clone(),
            owner: ctx.accounts.player_wallet.to_account_info(),
            token_program: ctx.accounts.token_2022_program.to_account_info(),
        };

        resource_manager::cpi::burn_resource(
            CpiContext::new_with_signer(
                ctx.accounts.resource_manager_program.to_account_info(),
                burn_accounts,
                signer_seeds,
            ),
            resource_id as u8,
            amount,
        )?;
    }

    // Mint the NFT via item_nft CPI.
    let mint_accounts = MintNft {
        payer: ctx.accounts.player_wallet.to_account_info(),
        recipient: ctx.accounts.player_wallet.to_account_info(),
        cpi_auth: ctx.accounts.cpi_auth.to_account_info(),
        nft_mint: ctx.accounts.nft_mint.to_account_info(),
        recipient_nft_ata: ctx.accounts.recipient_nft_ata.to_account_info(),
        nft_authority: ctx.accounts.nft_authority.to_account_info(),
        metadata: ctx.accounts.metadata.to_account_info(),
        master_edition: ctx.accounts.master_edition.to_account_info(),
        token_metadata_program: ctx.accounts.token_metadata_program.to_account_info(),
        item_metadata: ctx.accounts.item_metadata.to_account_info(),
        associated_token_program: ctx.accounts.associated_token_program.to_account_info(),
        token_program: ctx.accounts.token_program.to_account_info(),
        system_program: ctx.accounts.system_program.to_account_info(),
    };

    item_nft::cpi::mint_nft(
        CpiContext::new_with_signer(
            ctx.accounts.item_nft_program.to_account_info(),
            mint_accounts,
            signer_seeds,
        ),
        item_type,
    )?;

    Ok(())
}
